
POST http://localhost:3000/api/authenticate HTTP/1.1
Content-Type: application/json

{
    "email":"Skagen21@gmail.com",
    "password":"strange123"
}

###
POST http://localhost:3000/api/follow HTTP/1.1
Content-Type: application/json
Authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY0NjQwOTY5NjgyMCwiaXNzIjoicmV1bmlvbiIsInR5cGUiOiJhdCIsImV4cCI6MTY0NjQwOTc4MzIyMH0.1uYAWed4l5dkfsqk9YiwKS3YKABT_YjhiHDywLJHLkPHBaGKiN9WiHdza5l0Gq74zsLAa-qNKbe8erxH6arHK0iLctY-gKpVV_G8g8NAgguzYqFdYM3Q-F8byUOGS8HffyqlOPPvmwJZbXvuQiZccQdm1ZXRN_xtpt3b5GyODcC_UoQ_f6AGzGaVjkVTbbr9vLzZZPd3CiYQn_ml9O-2d8pTT34SDpzVeAaP6pVaRffGdfESBIpuV6TQigpqeAOOQqwlXxL2wP7F8_aIhogvKgu3d5RKa3kGJXIWkU47HxgwEZvCFombVyiWr1Fp7F65F1-Bqw9uGEpHfMAX8HaNqZ0pzoFDb6gvbPYHf_91JrCARxP9p2vGb4GH41Eg4qcW9vUfMI6CUez40EYG4TQelbZXyNPSu-6_bKsPsMv-B4xoTl8i9NIVy8oAjv5tjWrORiraamUnkV4-Awlp3IhSAEm4s6Ls73zB4z9Y9FuJL2emmwFE8r1RaZxR4zkDE_dsRuLIx-F5qnJmh-hFhInHJBJJLngPxXQfvxljGXE8RTlLohDOtaGKmk3N4bR2sgMSIEOwVq4THBU1OEfu4-SpqD_9t8sNxC55_x70CYtR6-Dy4B0tg0ilK0N5AE81nDbQ90A8KX62G7UNgrY3ytytHKC8Dt0t7vabVrQa2Q9Jzog

{
    "id":"2"
}

################################

POST http://localhost:3000/api/unfollow HTTP/1.1
Content-Type: application/json
Authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY0NjQwMDYzOTEwNSwiaXNzIjoicmV1bmlvbiIsInR5cGUiOiJhdCIsImV4cCI6MTY0NjQwMDcyNTUwNX0.WvCyRZYZs7l1KCz2hfshweXPthxWqDTGhuTMEHBEwOQNizIoL6RK12sTx6hG7Mgqat4fG1KgkN542QJXA5fYvcj_UCiFSYKbaeZLHtgpTNjvQbfHRwIT1fctecRVlT5CDbdpLJKTOeLhUjDvheB028hWXBATx4CuT7Y8nCyE2C6kWB8ImyeX8bEtl2I1uZv0oJJEfiQCJuk_nsULwwSC58Sj9U8e4HyAP7kDlhLsjghGuTRpm7WMMglvS7kUuHgrxGR-HGfjAgOVJq5TAwLuRUJbsIRlHDm4EHWDek67jAIGrJtO1jhrZJ2UfMx_h-_KbJPKtI3hWi0XmVi3eRyzryzr1HGzx4ErIe1hHtg269LpVPttOl2If45n0sTtY2hO-v_UJvXxWgNjq0XqyiYlQEn1DcvMbPU_2pHInckpkTL1wdBwDSkm195s5QLtX5ukiJglpR1RIkHu1-vti5mKM1u-7VRaa6paT3T9BzSzRtyJCbIZBIu5SN4X5LDOP1C2aOZublXZMFKECZwNU60kNr6oC5_MaLznacy8FJcq8YmLBem6DwtZcPBW2DKYsYkkmxzOIoFNbqRArG1TE31A6Y52BpmDtYVYmCqsCUqluxr3eQPc_WIzxeCYPE9n6VT8VPAiW8NowcD-gOdTSei8uZ9F5J4gwYAR48HVfV4kH3M


{
    "id":"2"
}

#######
GET http://localhost:3000/api/user HTTP/1.1
Content-Type: application/json
Authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY0NjQwMDYzOTEwNSwiaXNzIjoicmV1bmlvbiIsInR5cGUiOiJhdCIsImV4cCI6MTY0NjQwMDcyNTUwNX0.WvCyRZYZs7l1KCz2hfshweXPthxWqDTGhuTMEHBEwOQNizIoL6RK12sTx6hG7Mgqat4fG1KgkN542QJXA5fYvcj_UCiFSYKbaeZLHtgpTNjvQbfHRwIT1fctecRVlT5CDbdpLJKTOeLhUjDvheB028hWXBATx4CuT7Y8nCyE2C6kWB8ImyeX8bEtl2I1uZv0oJJEfiQCJuk_nsULwwSC58Sj9U8e4HyAP7kDlhLsjghGuTRpm7WMMglvS7kUuHgrxGR-HGfjAgOVJq5TAwLuRUJbsIRlHDm4EHWDek67jAIGrJtO1jhrZJ2UfMx_h-_KbJPKtI3hWi0XmVi3eRyzryzr1HGzx4ErIe1hHtg269LpVPttOl2If45n0sTtY2hO-v_UJvXxWgNjq0XqyiYlQEn1DcvMbPU_2pHInckpkTL1wdBwDSkm195s5QLtX5ukiJglpR1RIkHu1-vti5mKM1u-7VRaa6paT3T9BzSzRtyJCbIZBIu5SN4X5LDOP1C2aOZublXZMFKECZwNU60kNr6oC5_MaLznacy8FJcq8YmLBem6DwtZcPBW2DKYsYkkmxzOIoFNbqRArG1TE31A6Y52BpmDtYVYmCqsCUqluxr3eQPc_WIzxeCYPE9n6VT8VPAiW8NowcD-gOdTSei8uZ9F5J4gwYAR48HVfV4kH3M


{
    
}


#####

POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json
Authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY0NjQwMDYzOTEwNSwiaXNzIjoicmV1bmlvbiIsInR5cGUiOiJhdCIsImV4cCI6MTY0NjQwMDcyNTUwNX0.WvCyRZYZs7l1KCz2hfshweXPthxWqDTGhuTMEHBEwOQNizIoL6RK12sTx6hG7Mgqat4fG1KgkN542QJXA5fYvcj_UCiFSYKbaeZLHtgpTNjvQbfHRwIT1fctecRVlT5CDbdpLJKTOeLhUjDvheB028hWXBATx4CuT7Y8nCyE2C6kWB8ImyeX8bEtl2I1uZv0oJJEfiQCJuk_nsULwwSC58Sj9U8e4HyAP7kDlhLsjghGuTRpm7WMMglvS7kUuHgrxGR-HGfjAgOVJq5TAwLuRUJbsIRlHDm4EHWDek67jAIGrJtO1jhrZJ2UfMx_h-_KbJPKtI3hWi0XmVi3eRyzryzr1HGzx4ErIe1hHtg269LpVPttOl2If45n0sTtY2hO-v_UJvXxWgNjq0XqyiYlQEn1DcvMbPU_2pHInckpkTL1wdBwDSkm195s5QLtX5ukiJglpR1RIkHu1-vti5mKM1u-7VRaa6paT3T9BzSzRtyJCbIZBIu5SN4X5LDOP1C2aOZublXZMFKECZwNU60kNr6oC5_MaLznacy8FJcq8YmLBem6DwtZcPBW2DKYsYkkmxzOIoFNbqRArG1TE31A6Y52BpmDtYVYmCqsCUqluxr3eQPc_WIzxeCYPE9n6VT8VPAiW8NowcD-gOdTSei8uZ9F5J4gwYAR48HVfV4kH3M


{
    "title":"Got Hired In a Company",
    "description":"Very happy to share with you that i am hired in a company"
}

###
DELETE  http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json
Authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY0NjQwMDYzOTEwNSwiaXNzIjoicmV1bmlvbiIsInR5cGUiOiJhdCIsImV4cCI6MTY0NjQwMDcyNTUwNX0.WvCyRZYZs7l1KCz2hfshweXPthxWqDTGhuTMEHBEwOQNizIoL6RK12sTx6hG7Mgqat4fG1KgkN542QJXA5fYvcj_UCiFSYKbaeZLHtgpTNjvQbfHRwIT1fctecRVlT5CDbdpLJKTOeLhUjDvheB028hWXBATx4CuT7Y8nCyE2C6kWB8ImyeX8bEtl2I1uZv0oJJEfiQCJuk_nsULwwSC58Sj9U8e4HyAP7kDlhLsjghGuTRpm7WMMglvS7kUuHgrxGR-HGfjAgOVJq5TAwLuRUJbsIRlHDm4EHWDek67jAIGrJtO1jhrZJ2UfMx_h-_KbJPKtI3hWi0XmVi3eRyzryzr1HGzx4ErIe1hHtg269LpVPttOl2If45n0sTtY2hO-v_UJvXxWgNjq0XqyiYlQEn1DcvMbPU_2pHInckpkTL1wdBwDSkm195s5QLtX5ukiJglpR1RIkHu1-vti5mKM1u-7VRaa6paT3T9BzSzRtyJCbIZBIu5SN4X5LDOP1C2aOZublXZMFKECZwNU60kNr6oC5_MaLznacy8FJcq8YmLBem6DwtZcPBW2DKYsYkkmxzOIoFNbqRArG1TE31A6Y52BpmDtYVYmCqsCUqluxr3eQPc_WIzxeCYPE9n6VT8VPAiW8NowcD-gOdTSei8uZ9F5J4gwYAR48HVfV4kH3M


{
    "postId":"2"
}

################################
POST http://localhost:3000/api/like HTTP/1.1
Content-Type: application/json
Authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY0NjQwMDYzOTEwNSwiaXNzIjoicmV1bmlvbiIsInR5cGUiOiJhdCIsImV4cCI6MTY0NjQwMDcyNTUwNX0.WvCyRZYZs7l1KCz2hfshweXPthxWqDTGhuTMEHBEwOQNizIoL6RK12sTx6hG7Mgqat4fG1KgkN542QJXA5fYvcj_UCiFSYKbaeZLHtgpTNjvQbfHRwIT1fctecRVlT5CDbdpLJKTOeLhUjDvheB028hWXBATx4CuT7Y8nCyE2C6kWB8ImyeX8bEtl2I1uZv0oJJEfiQCJuk_nsULwwSC58Sj9U8e4HyAP7kDlhLsjghGuTRpm7WMMglvS7kUuHgrxGR-HGfjAgOVJq5TAwLuRUJbsIRlHDm4EHWDek67jAIGrJtO1jhrZJ2UfMx_h-_KbJPKtI3hWi0XmVi3eRyzryzr1HGzx4ErIe1hHtg269LpVPttOl2If45n0sTtY2hO-v_UJvXxWgNjq0XqyiYlQEn1DcvMbPU_2pHInckpkTL1wdBwDSkm195s5QLtX5ukiJglpR1RIkHu1-vti5mKM1u-7VRaa6paT3T9BzSzRtyJCbIZBIu5SN4X5LDOP1C2aOZublXZMFKECZwNU60kNr6oC5_MaLznacy8FJcq8YmLBem6DwtZcPBW2DKYsYkkmxzOIoFNbqRArG1TE31A6Y52BpmDtYVYmCqsCUqluxr3eQPc_WIzxeCYPE9n6VT8VPAiW8NowcD-gOdTSei8uZ9F5J4gwYAR48HVfV4kH3M


{
    "postId":"1"
}

################################

POST http://localhost:3000/api/unlike HTTP/1.1
Content-Type: application/json
Authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY0NjQwMDYzOTEwNSwiaXNzIjoicmV1bmlvbiIsInR5cGUiOiJhdCIsImV4cCI6MTY0NjQwMDcyNTUwNX0.WvCyRZYZs7l1KCz2hfshweXPthxWqDTGhuTMEHBEwOQNizIoL6RK12sTx6hG7Mgqat4fG1KgkN542QJXA5fYvcj_UCiFSYKbaeZLHtgpTNjvQbfHRwIT1fctecRVlT5CDbdpLJKTOeLhUjDvheB028hWXBATx4CuT7Y8nCyE2C6kWB8ImyeX8bEtl2I1uZv0oJJEfiQCJuk_nsULwwSC58Sj9U8e4HyAP7kDlhLsjghGuTRpm7WMMglvS7kUuHgrxGR-HGfjAgOVJq5TAwLuRUJbsIRlHDm4EHWDek67jAIGrJtO1jhrZJ2UfMx_h-_KbJPKtI3hWi0XmVi3eRyzryzr1HGzx4ErIe1hHtg269LpVPttOl2If45n0sTtY2hO-v_UJvXxWgNjq0XqyiYlQEn1DcvMbPU_2pHInckpkTL1wdBwDSkm195s5QLtX5ukiJglpR1RIkHu1-vti5mKM1u-7VRaa6paT3T9BzSzRtyJCbIZBIu5SN4X5LDOP1C2aOZublXZMFKECZwNU60kNr6oC5_MaLznacy8FJcq8YmLBem6DwtZcPBW2DKYsYkkmxzOIoFNbqRArG1TE31A6Y52BpmDtYVYmCqsCUqluxr3eQPc_WIzxeCYPE9n6VT8VPAiW8NowcD-gOdTSei8uZ9F5J4gwYAR48HVfV4kH3M


{
    "postId":"1"
}

################################

POST http://localhost:3000/api/comment HTTP/1.1
Content-Type: application/json
Authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY0NjQwMDYzOTEwNSwiaXNzIjoicmV1bmlvbiIsInR5cGUiOiJhdCIsImV4cCI6MTY0NjQwMDcyNTUwNX0.WvCyRZYZs7l1KCz2hfshweXPthxWqDTGhuTMEHBEwOQNizIoL6RK12sTx6hG7Mgqat4fG1KgkN542QJXA5fYvcj_UCiFSYKbaeZLHtgpTNjvQbfHRwIT1fctecRVlT5CDbdpLJKTOeLhUjDvheB028hWXBATx4CuT7Y8nCyE2C6kWB8ImyeX8bEtl2I1uZv0oJJEfiQCJuk_nsULwwSC58Sj9U8e4HyAP7kDlhLsjghGuTRpm7WMMglvS7kUuHgrxGR-HGfjAgOVJq5TAwLuRUJbsIRlHDm4EHWDek67jAIGrJtO1jhrZJ2UfMx_h-_KbJPKtI3hWi0XmVi3eRyzryzr1HGzx4ErIe1hHtg269LpVPttOl2If45n0sTtY2hO-v_UJvXxWgNjq0XqyiYlQEn1DcvMbPU_2pHInckpkTL1wdBwDSkm195s5QLtX5ukiJglpR1RIkHu1-vti5mKM1u-7VRaa6paT3T9BzSzRtyJCbIZBIu5SN4X5LDOP1C2aOZublXZMFKECZwNU60kNr6oC5_MaLznacy8FJcq8YmLBem6DwtZcPBW2DKYsYkkmxzOIoFNbqRArG1TE31A6Y52BpmDtYVYmCqsCUqluxr3eQPc_WIzxeCYPE9n6VT8VPAiW8NowcD-gOdTSei8uZ9F5J4gwYAR48HVfV4kH3M

{

}

################################

GET http://localhost:3000/api/posts/1 HTTP/1.1
Content-Type: application/json
Authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY0NjQwMDYzOTEwNSwiaXNzIjoicmV1bmlvbiIsInR5cGUiOiJhdCIsImV4cCI6MTY0NjQwMDcyNTUwNX0.WvCyRZYZs7l1KCz2hfshweXPthxWqDTGhuTMEHBEwOQNizIoL6RK12sTx6hG7Mgqat4fG1KgkN542QJXA5fYvcj_UCiFSYKbaeZLHtgpTNjvQbfHRwIT1fctecRVlT5CDbdpLJKTOeLhUjDvheB028hWXBATx4CuT7Y8nCyE2C6kWB8ImyeX8bEtl2I1uZv0oJJEfiQCJuk_nsULwwSC58Sj9U8e4HyAP7kDlhLsjghGuTRpm7WMMglvS7kUuHgrxGR-HGfjAgOVJq5TAwLuRUJbsIRlHDm4EHWDek67jAIGrJtO1jhrZJ2UfMx_h-_KbJPKtI3hWi0XmVi3eRyzryzr1HGzx4ErIe1hHtg269LpVPttOl2If45n0sTtY2hO-v_UJvXxWgNjq0XqyiYlQEn1DcvMbPU_2pHInckpkTL1wdBwDSkm195s5QLtX5ukiJglpR1RIkHu1-vti5mKM1u-7VRaa6paT3T9BzSzRtyJCbIZBIu5SN4X5LDOP1C2aOZublXZMFKECZwNU60kNr6oC5_MaLznacy8FJcq8YmLBem6DwtZcPBW2DKYsYkkmxzOIoFNbqRArG1TE31A6Y52BpmDtYVYmCqsCUqluxr3eQPc_WIzxeCYPE9n6VT8VPAiW8NowcD-gOdTSei8uZ9F5J4gwYAR48HVfV4kH3M

{

}


################################

################################
GET http://localhost:3000/api/all_posts HTTP/1.1
Content-Type: application/json
Authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTY0NjQwMDYzOTEwNSwiaXNzIjoicmV1bmlvbiIsInR5cGUiOiJhdCIsImV4cCI6MTY0NjQwMDcyNTUwNX0.WvCyRZYZs7l1KCz2hfshweXPthxWqDTGhuTMEHBEwOQNizIoL6RK12sTx6hG7Mgqat4fG1KgkN542QJXA5fYvcj_UCiFSYKbaeZLHtgpTNjvQbfHRwIT1fctecRVlT5CDbdpLJKTOeLhUjDvheB028hWXBATx4CuT7Y8nCyE2C6kWB8ImyeX8bEtl2I1uZv0oJJEfiQCJuk_nsULwwSC58Sj9U8e4HyAP7kDlhLsjghGuTRpm7WMMglvS7kUuHgrxGR-HGfjAgOVJq5TAwLuRUJbsIRlHDm4EHWDek67jAIGrJtO1jhrZJ2UfMx_h-_KbJPKtI3hWi0XmVi3eRyzryzr1HGzx4ErIe1hHtg269LpVPttOl2If45n0sTtY2hO-v_UJvXxWgNjq0XqyiYlQEn1DcvMbPU_2pHInckpkTL1wdBwDSkm195s5QLtX5ukiJglpR1RIkHu1-vti5mKM1u-7VRaa6paT3T9BzSzRtyJCbIZBIu5SN4X5LDOP1C2aOZublXZMFKECZwNU60kNr6oC5_MaLznacy8FJcq8YmLBem6DwtZcPBW2DKYsYkkmxzOIoFNbqRArG1TE31A6Y52BpmDtYVYmCqsCUqluxr3eQPc_WIzxeCYPE9n6VT8VPAiW8NowcD-gOdTSei8uZ9F5J4gwYAR48HVfV4kH3M

{

}

